### ISSUE TITLE
`porter update` throws error

### ISSUE THREAD

**Issue by anukul** [porter-dev/porter#1025]
# Description

`porter update` throws error

```
Error: repository name must be canonical
```

![image](https://user-images.githubusercontent.com/44864521/129071909-22c7c549-a8f4-430f-94e6-fa7ccd3b11ed.png)

Can also be seen at https://github.com/anukul/gin-example/runs/3303306850?check_suite_focus=true

# Location

- [ ] Browser
- [x] CLI
- [ ] API

# Steps to reproduce

1. Connect a docker image repository from Docker Hub
2. Deploy app from git repository

# Additional Details

Image repository used: https://hub.docker.com/repository/docker/anukulsangwan/gin-example
Git repository used: https://github.com/anukul/gin-example

**Comment by anukul** [comment]
Tried running this locally in debug mode.

Error is thrown by docker's [reference.ParseNamed](https://sourcegraph.com/github.com/kubernetes/kubernetes@v1.22.0/-/blob/vendor/github.com/docker/distribution/reference/reference.go?L247) which we're calling from [GetServerURLFromTag](https://sourcegraph.com/github.com/porter-dev/porter@v0.7.0/-/blob/cli/cmd/docker/agent.go?L254&utm_product_name=IntelliJ+IDEA&utm_product_version=IntelliJ+IDEA&utm_source=JetBrains-v1.2.0#L253:6-253:25):

![image](https://user-images.githubusercontent.com/44864521/129077226-33e4f3ca-8dea-4c6d-b31f-8c2a0c84b9ce.png)

No error if I add this line before calling `GetServerURLFromTag`:

```go
image = strings.Replace(image, "index.docker.io", "docker.io", -1)
```

**Comment by anukul** [comment]
Tried running this locally in debug mode.

Error is thrown by docker's [reference.ParseNamed](https://sourcegraph.com/github.com/kubernetes/kubernetes@v1.22.0/-/blob/vendor/github.com/docker/distribution/reference/reference.go?L247) which we're calling from [GetServerURLFromTag](https://sourcegraph.com/github.com/porter-dev/porter@v0.7.0/-/blob/cli/cmd/docker/agent.go?L254&utm_product_name=IntelliJ+IDEA&utm_product_version=IntelliJ+IDEA&utm_source=JetBrains-v1.2.0#L253:6-253:25):

![image](https://user-images.githubusercontent.com/44864521/129077226-33e4f3ca-8dea-4c6d-b31f-8c2a0c84b9ce.png)

No error if I add this line in `GetServerURLFromTag` before calling `reference.ParseNamed`:

```go
image = strings.Replace(image, "index.docker.io", "docker.io", -1)
```

**Comment by mnafees** [comment]
Fixed with https://github.com/porter-dev/porter/pull/2359
