### ISSUE TITLE
Triggering manual job run reset cron schedule to every 5m

### ISSUE THREAD

**Issue by jusrhee** [porter-dev/porter#1057]
# Description

If a job is created with a cron schedule (e.g., every 20m), if the user just expands the job and triggers a manual run (without viewing any of the other tabs) the schedule seems to be reset to every 5m

# Location

- [X] Browser
- [ ] CLI
- [ ] API

# Steps to reproduce

1. Create a cron with a 20m (or other) schedule
2. Expand job chart and trigger a manual run (without viewing the other tabs)
3. Schedule is reset to 5m

# Additional Details

**Comment by abelanger5** [comment]
Closed by #1058
