### ISSUE TITLE
porter run interactive shell doesnt wrap text or resize to terminal

### ISSUE THREAD

**Issue by joegilley** [porter-dev/porter#1069]
# Description

![45bc8ba8e98e1e713a8a5c85a3f1cab2](https://user-images.githubusercontent.com/1476969/129817261-20a260fa-4551-4620-aeff-918bcdc1cdd3.gif)

# Location

- [ ] Browser
- [x] CLI
- [ ] API

tested on 90f60a5c766ca735a8d04e5fc848c3d53ee58429

# Steps to reproduce

1. Run `porter run anyreleasewithshell bash`
1. type a bunch of stuff

# Additional Details

## Expected behavior

<img width="517" alt="image" src="https://user-images.githubusercontent.com/1476969/129817354-586f6095-7840-40bb-811a-faf125f085bd.png">

expect content to wrap, as it does in `kubectl run`

**Comment by abelanger5** [comment]
Closed by #1070 -- released in `v0.8.0`!
