### ISSUE TITLE
[Docs]: Wrong YAML keys on Exposing a Web Application on a Custom Domain example

### ISSUE THREAD

**Issue by chuma9615** [porter-dev/porter#1115]
# Description

It seems that the [example](https://docs.porter.run/docs/deploying-from-the-cli#web-exposing-a-web-application-on-a-custom-domain) on the docs has the wrong key on the YAML, it should be `hosts` instead of `custom_paths`

# Location
- [x] Documentation
- [ ] Browser
- [ ] CLI
- [ ] API

# Steps to reproduce

1. Deploy a new app with the example `values.yaml` file exposed in the aforementioned link
2. Watch it fail
3. Deploy a new app changing the key from `custom_paths` to `hosts`

# Additional Details

**Comment by abelanger5** [comment]
Ah, good catch @chuma9615 -- let me know if you'd like to make a PR that fixes this for the file: https://github.com/porter-dev/porter/blob/master/docs/deploy/applications/deploying-from-the-cli.md. 

Also, feel free to suggest changes to this doc if you found anything difficult to follow!

**Comment by chuma9615** [comment]
Got it, I'll open a PR.

Sure thing, keep it up boys!

**Comment by abelanger5** [comment]
Closed by #1117
