### ISSUE TITLE
Release info fails to load, request sent with empty namespace

### ISSUE THREAD

**Issue by abelanger5** [porter-dev/porter#129]
Getting the error:

```txt
porter_1       | {"level":"warn","error":"get: failed to get \"sh.helm.release.v1.velero.v2\": an empty namespace may not be set when a resource name is provided","errExt":"{\"code\":602,\"errors\":[\"release not found\"]}","time":"2020-12-17T13:07:42Z"}

porter_1       | {"level":"info","received_time":"2020-12-17T13:07:42Z","method":"GET","url":"/api/projects/1/releases/velero/2?namespace=&cluster_id=4&storage=secret","header_size":667,"body_size":0,"agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36","referer":"http://localhost:8080/dashboard","proto":"HTTP/1.1","status":404,"resp_header_size":47,"resp_body_size":43,"latency":63.5042,"time":"2020-12-17T13:07:42Z"}
```

The request (sent in the method `getChartData` in the `ExpandedChart` component) is sent as `/api/projects/1/releases/velero/2?namespace=&cluster_id=4&storage=secret`--for some reason the namespace isn't being passed in via props. 

**Note: this only happens after clicking into a chart when the namespace selector is "All". It does not happen after a specific namespace has been selected and you click into a chart.**

**Comment by sunguroku** [comment]
This should already be fixed on `master` - were you on a different branch?
