### ISSUE TITLE
Pods in "waiting" state added incorrectly to status tab

### ISSUE THREAD

**Issue by abelanger5** [porter-dev/porter#138]
For some reason the following pod stuck in "waiting" is added to the status tab:

<img width="1176" alt="Screen Shot 2020-12-17 at 8 50 25 AM" src="https://user-images.githubusercontent.com/25448214/102496240-286bb300-4045-11eb-90d0-96e2274a37c6.png">

However, the output of `kubectl get all -n velero`:

```txt
NAME                          READY   STATUS    RESTARTS   AGE
pod/velero-6c785494d7-8qnkt   1/1     Running   0          24h

NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/velero   1/1     1            1           24h

NAME                                DESIRED   CURRENT   READY   AGE
replicaset.apps/velero-6c785494d7   1         1         1       24h
```

**Comment by sunguroku** [comment]
this looks like an edge case when the pod with `ImagePullBackOffError` persists for a brief while before the controller kills it - can you check if it still persists?

**Comment by abelanger5** [comment]
Resolved by live-status tab updates.
