### ISSUE TITLE
Launch template cluster selector is ignored (only deploys to current cluster)

### ISSUE THREAD

**Issue by jusrhee** [porter-dev/porter#144]

**Comment by anukul** [comment]
Hi! Can I try this?

I see some instances of `cluster_id: currentCluster.id` in [LaunchFlow.tsx](https://github.com/porter-dev/porter/blob/v0.4.4/dashboard/src/main/home/launch/launch-flow/LaunchFlow.tsx)

**Comment by abelanger5** [comment]
Hi @anukul! I actually believe this has been fixed, since the cluster selector sets the `currentCluster`. I'll let @jusrhee reopen if this is not the case. 

Would love your help on other issues though!
