### ISSUE TITLE
Connect to existing cluster

### ISSUE THREAD

**Issue by tonxxd** [porter-dev/porter#1948]
Hi and thanks for this amazing project!

Would it be possible to connect to an existing cluster and "manage applications" through the porter UI in a custom namespace (or multiple namespaces) so that we don't interfere with existing resources deployed? 
In 2 words, installing porter on a custom namespace in an already existing cluster

**Comment by oflynned** [comment]
+1

**Comment by Wulfheart** [comment]
As stated [here](https://www.reddit.com/r/selfhosted/comments/kuqw50/comment/giuq7af/) it is supported.

**Comment by mnafees** [comment]
For future reference: this is possible with the `porter connect kubeconfig` CLI command as is documented at https://docs.porter.run/cli/command-reference/porter-connect/#porter-connect-kubeconfig
