### ISSUE TITLE
Rename project to avoid name clash

### ISSUE THREAD

**Issue by kkapelon** [porter-dev/porter#198]
There is already a project with the same name from Microsoft started in November 2018 (so almost two years before this project).

- https://porter.sh/
- https://github.com/getporter/porter

I suggest you rename the project (since they are both devops platform/tools) because now people will be confused when they search for

"porter cloud", "porter installation", "porter requirements" and other similar terms.

**Comment by abelanger5** [comment]
You're right, that is confusing. We were unfortunately well into development before coming across porter.sh, and changing the name several months into development isn't as easy as it sounds. 

It's something we'll certainly discuss -- thanks for letting us know about the confusion.
