### ISSUE TITLE
Welcome API fails when running in docker local

### ISSUE THREAD

**Issue by dustinblackman** [porter-dev/porter#2346]
# Description

The welcome view that is shown after logging in to Porter for the first time when running locally fails to successfully create a project. The `/api/welcome` endpoint fails with a 500 error, with logs stating the following:

```
{"level":"warn","internal_error":"Get \"?company=https%3A%2F%2Fporter.run&email=test%40test.com&isCompany=true&name=Bob&role=founder\": unsupported protocol scheme \"\"","external_error":"An internal error occurred.","user_id":1,"method":"POST","url":"/api/welcome","time":"2022-08-30T14:57:07Z"}
{"level":"info","latency":0.137051,"status":500,"user_id":1,"method":"POST","url":"/api/welcome","time":"2022-08-30T14:57:07Z"}
```

# Location

- [X] Browser
- [ ] CLI
- [X] API

# Steps to reproduce

1. Run Porter locally with Docker using the following commands

```sh
docker volume create porter_sqlite                                                                                                                                                          ✘ 130 tags/v0.35.0 ✱
docker run \
  --mount type=volume,source=porter_sqlite,target=/sqlite,readonly=false \
  -e REDIS_ENABLED=false \
  -e SQL_LITE_PATH=/sqlite/porter.db \
  -p 8080:8080 \
  porter1/porter:v0.36.0
```

2. Open `https://127.0.0.1:8080`, click signup, and create an account.
3. When the welcome page loads, fill in the form and hit submit.
4. Verify in network tools and in logs that the request has failed.

# Additional Details

## Screenshots

<img width="1784" alt="image" src="https://user-images.githubusercontent.com/5246169/187471591-303303cc-7409-4c12-a1ec-87b15bca8e38.png">

## Logs

```
{"level":"info","time":"2022-08-30T15:02:40Z","message":"running migrations"}
{"level":"info","time":"2022-08-30T15:02:41Z","message":"Starting server :8080"}
{"level":"warn","internal_error":"stored cookie was not authenticated","external_error":"Forbidden","method":"GET","url":"/api/users/current","time":"2022-08-30T15:02:50Z"}
{"level":"info","latency":0.096336,"status":200,"method":"GET","url":"/api/metadata","time":"2022-08-30T15:02:50Z"}
{"level":"info","latency":0.025529,"status":200,"method":"GET","url":"/api/metadata","time":"2022-08-30T15:02:50Z"}
{"level":"warn","internal_error":"stored cookie was not authenticated","external_error":"Forbidden","method":"GET","url":"/api/users/current","time":"2022-08-30T15:02:52Z"}
{"level":"info","latency":0.010767,"status":200,"method":"GET","url":"/api/metadata","time":"2022-08-30T15:02:52Z"}
{"level":"info","latency":0.014472,"status":200,"method":"GET","url":"/api/metadata","time":"2022-08-30T15:02:52Z"}
{"level":"error","time":"2022-08-30T15:02:55Z","message":"Analytics not enabled"}
{"level":"error","time":"2022-08-30T15:02:55Z","message":"Analytics not enabled"}
{"level":"info","latency":43.178085,"status":200,"method":"POST","url":"/api/users","time":"2022-08-30T15:02:55Z"}
{"level":"info","latency":0.010957,"status":200,"user_id":1,"method":"GET","url":"/api/users/current","time":"2022-08-30T15:02:55Z"}
{"level":"info","latency":0.009141,"status":200,"user_id":1,"method":"GET","url":"/api/can_create_project","time":"2022-08-30T15:02:55Z"}
{"level":"info","latency":0.017068,"status":200,"method":"GET","url":"/api/metadata","time":"2022-08-30T15:02:55Z"}
{"level":"info","latency":0.680781,"status":200,"user_id":1,"method":"GET","url":"/api/projects","time":"2022-08-30T15:02:55Z"}
{"level":"warn","internal_error":"Get \"?company=https%3A%2F%2Fporter.run&email=test%40test.com&isCompany=true&name=Jim&role=founder\": unsupported protocol scheme \"\"","external_error":"An internal error occurred.","user_id":1,"method":"POST","url":"/api/welcome","time":"2022-08-30T15:03:03Z"}
{"level":"info","latency":0.172719,"status":500,"user_id":1,"method":"POST","url":"/api/welcome","time":"2022-08-30T15:03:03Z"}
```

**Comment by dustinblackman** [comment]
Ah, the issue is that config `WELCOME_FORM_WEBHOOK` is empty by default, and [is not](https://github.com/porter-dev/porter/blob/7c96dc44987e3bb2fbc73d22ecc20267037aad57/api/server/handlers/user/welcome_webhook.go#L36) being checked before an attempting a request.

Lazy workaround is setting `-e WELCOME_FORM_WEBHOOK="https://httpbin.org/get" ` when running with docker.

**Comment by dustinblackman** [comment]
This issue doesn't occur on master branch in the [dev environments](https://github.com/porter-dev/porter/pull/2348), yet `v0.36.0` was released just hours ago. I'm unsure why it's happening only on the release.

**Comment by abelanger5** [comment]
Hey @dustinblackman, thanks for the bug report! Is `WELCOME_FORM_WEBHOOK` set in your `./docker/.env` file? I'm not quite sure why this wouldn't be impacting the docker dev environments as well. 

That said, the easiest fix is probably to check for the webhook in the handler, as you mentioned. Let me know if you'd like to open up a PR, otherwise we'll pick this up for a patch release 👍

**Comment by dustinblackman** [comment]
@abelanger5 Ah okay! So I believe it's missing from the docs, which is why I initially had it missing. Not sure why it's acting different between the two environments.

I'd be happy to PR a fix, but depends on what the expectations are. Is `WELCOME_FORM_WEBHOOK` expected to be a required variable? If yes I can update docs and env setups. if no I can check if it exists first so the request doesn't fail.

**Comment by abelanger5** [comment]
No, it's not expected to be required. Checking it in the request definitely makes sense!
