### ISSUE TITLE
Deployments set to the incorrect namespace, default only

### ISSUE THREAD

**Issue by dustinblackman** [porter-dev/porter#2347]
# Description

Currently, any deploys using the provided application templates (web service, worker, job) will only deploy resources in to the `default` namespace, even if you've selected another namespace to deploy to. This also causes UI errors as it attempts to get information of the current deployment and fails as it doesn't exist in your selected namespace.

# Location

- [x] Browser
- [ ] CLI
- [ ] API

# Steps to reproduce

1. In the UI, click Launch Template, Web Service, and Launch Template.
2. Enter a name (`hello-world`), and an image (`tutum/hello-world`), and click next.
3. From the `namespace` dropdown menu, select `+ Add Namespace`. Enter `hello-world`. Be sure that `hello-world` is selected in the drop down menu after creation.
4. Deploy
5. Run `kubetctl get pods --all-namespaces` to see that `hello-world-web` was deployed in namespace`default`, not `hello-world`.

# Additional Details

## Screenshots

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/5246169/187531695-1e0708fe-c83c-4d31-81ef-9900a718a494.png">

<img width="946" alt="image" src="https://user-images.githubusercontent.com/5246169/187532165-d847c3b7-911b-4d24-b0cc-e97436315a88.png">

**Comment by dustinblackman** [comment]
Turns out this is a bug in the release available in brew. On master branch this isn't a problem. Sorry for the noise!

**Comment by abelanger5** [comment]
Hey @dustinblackman could you share the exact release image you're running? We're unable to replicate this in our latest release.

**Comment by dustinblackman** [comment]
After running the latest release I can't repo. Sorry for the noise!
