### ISSUE TITLE
CLI errors incorrectly piped to stdout instead of stderr

### ISSUE THREAD

**Issue by bbugh** [porter-dev/porter#2485]
# Description

The porter CLI commands are outputting errors to stdout instead of stderr. The expected behavior for a CLI is that any errors are piped to `stderr`. This is especially problematic for machine-readable formats like `--output json`. 

There is a workaround, but it requires parsing for error messages, and is not safe because the error message format could change or unhandled errors could occur.

# Location

- [ ] Browser
- [X] CLI
- [ ] API

# Steps to reproduce

```bash
bash-3.2$ porter get values $RELEASE --namespace $NS --output json 1> stdout.log 2> stderr.log
bash-3.2$ echo $?
1
```

Actual: 

```bash
bash-3.2$ cat stderr.log
bash-3.2$ cat stdout.log
Error: release not found
```

Expected:

```bash
bash-3.2$ cat stderr.log
Error: release not found
bash-3.2$ cat stdout.log
```

Hacky workaround:

```bash
porter get values $RELEASE --namespace $NS --output json | sed 's/^Error: .*?$//' | jq -r '.image.tag'
```

**Comment by mnafees** [comment]
Hi @bbugh, thank you for creating the issue on Github for this. This is a great catch and something that we should be strictly adhering to just like other CLI tools do. We will be pushing a fix for this in an upcoming CLI release and update this issue accordingly with the details of the same.

**Comment by bbugh** [comment]
Thanks for the quick fix!
