### ISSUE TITLE
Cluster list in Dashboard view fails to update on project change

### ISSUE THREAD

**Issue by jusrhee** [porter-dev/porter#281]
# Description

 

# Location

- [X] Browser 
- [ ] CLI 
- [ ] API

# Steps to reproduce

1. Select a project with at least one connected cluster and navigate to the "Dashboard" tab in the sidebar
2. Select a different project with at least one connected cluster
3. Note that cluster(s) from the previous project will still show

# Additional Details

When the project changes this view should be reset in general (including if the user was viewing the provisioner tab in the previous project -> reset to default cluster tab).

**Comment by josephch405** [comment]
I believe this should be irrelevant once #282 is patched per #284 ?
