### ISSUE TITLE
Cannot create first time run out of the box

### ISSUE THREAD

**Issue by wizpresso-steve-cy-fan** [porter-dev/porter#2896]
# Description

# Location

- [ ] Browser
- [x] CLI
- [ ] API

# Steps to reproduce

```
docker run \
  --mount type=volume,source=porter_sqlite,target=/sqlite,readonly=false \
  -e REDIS_ENABLED=false \
  -e SQL_LITE_PATH=/sqlite/porter.db \
  -p 8080:8080 \
  -d porter1/porter:v0.46.2
```

# Additional Details
```
root@WIZPRESSO-13-linux:/var/lib/docker/volumes/porter_sqlite/_data# docker logs 5698f73000caf0fbeaeb6e9feb2baf4b91ccb9a4b1bf73e7a82be8122ae8e210
{"level":"info","time":"2023-04-18T08:55:14Z","message":"running migrations"}
{"level":"fatal","error":"failed to drop fk constraint for assume role chains: SQL logic error: near \"CONSTRAINT\": syntax error (1)","time":"2023-04-18T08:55:16Z","message":"error updating cluster control plane tables"}
```
https://github.com/porter-dev/porter/blob/8099f362d3a9e28770d65bfacdbb3bdaa131c7d9/cmd/migrate/main.go#L52-L63
@stefanmcshane seems like you're the one to (git) blame

**Comment by wizpresso-steve-cy-fan** [comment]
Well just kidding I'm not kidding him because by the way this is by no mean a rookie mistake. SQLite does not support `DROP CONSTRAINT`, and you have to do a hefty table cloning process instead of dropping it. It's natural to make this mistake though, but I would suggest to use something like the migrator provided by GORM out of the box.

**Comment by stefanmcshane** [comment]
The Porter API should be used with Postgres. SQLLite support is only used for testing purposes.
