### ISSUE TITLE
First-class support for monorepos in CI

### ISSUE THREAD

**Issue by sunguroku** [porter-dev/porter#339]
# Location

- [x] Browser
- [ ] CLI
- [x] API

# Requirements
Monorepo's with multiple microservices are currently supported on Porter, but falls short with build context. ATM, the `docker build` command in the CI file defaults to root folder with no option to customize it. For monorepos, we need to support configuring a different path for the build context.

# Additional Details
Setting the build context should be intuitive, not sure what the most elegant way to do this is. Fallback option is explicitly saying **Set build context** before selecting Dockerfile, but doesn't seem that ideal.

**Comment by josephch405** [comment]
Fixed by #345
