### ISSUE TITLE
Environment Variables and Secrets

### ISSUE THREAD

**Issue by Aleksion** [porter-dev/porter#365]
# Location

- [x] Browser
- [ ] CLI
- [ ] API

# Requirements
There doesn't seem to be a way to encrypt secrets in the porter interface.
I believe secrets can be saved as base64 in k8s and then served and decrypted to the container. I would like to be able to add those secrets and then use them as environment variables in my service. This would make them not show up to all users in both the helm chart and the environment table

# Additional Details

**Comment by abelanger5** [comment]
This was added in a recent release: https://docs.getporter.dev/docs/using-environment-groups#-creating-secret-environment-variables. Thanks for the suggestion!
