### ISSUE TITLE
Disable linking the same git repository or docker registry twice

### ISSUE THREAD

**Issue by sunguroku** [porter-dev/porter#369]
# Location

- [x] Browser
- [ ] CLI
- [x] API

# Motivation
From the integrations tab or from the CLI, connecting the same github account or docker registry twice results in duplicate entries.
# Requirements
Each integration must be unique to avoid duplicates and flooding of registries/repositories a user can select from.
# Additional Details

**Comment by abelanger5** [comment]
This is resolved -- we still allow duplicate Github accounts/registries, but users can remove separate accounts in the Integrations tab. We remove duplicate entries from the rendered registries and Github repositories.
