### ISSUE TITLE
Linked GCR repositories do not show in browser view

### ISSUE THREAD

**Issue by kevinhu** [porter-dev/porter#371]
# Description

When connected to Google Cloud Registry, the images under the selected registry do not show up in the browser (under Integrations > Docker Registry > [registry_name], and the list of images is empty when creating a new deployment).

However, copy-pasting the image URL still creates successful deploys.

# Location

- [x] Browser
- [ ] CLI
- [ ] API

# Steps to reproduce

1. Connect Porter to GCR with CIA (as outlined in https://docs.getporter.dev/docs/linking-an-existing-docker-container-registry#google-container-registry-gcr). Alternatively, connect to GCR in the browser through Integrations > Docker Registry > Add a Registry
2. Attempt to create a new deployment or view a list of images under Integrations > Docker Registry > [registry_name]

# Additional Details

**Comment by smashah** [comment]
@kevinhu can you confirm what permissions you are setting for the service account related to the integration?

**Comment by abelanger5** [comment]
@kevinhu I believe I found the root cause of this issue, this is likely due to the Cloud Resource Manager API not being enabled: https://console.cloud.google.com/apis/api/cloudresourcemanager.googleapis.com/overview. 

If you get the chance, could you check if this fixes the issue?

**Comment by candh** [comment]
@abelanger5 i was having the same, enabling the API solved it. thanks!

**Comment by sunguroku** [comment]
@candh The docs have been updated and now lists all the APIs that need to be enabled. You can find it here! https://docs.getporter.dev/docs/getting-started-on-gcp#prerequisites

**Comment by kevinhu** [comment]
Yep, can confirm this works. Thank you so much!
