### ISSUE TITLE
can't login with github 

### ISSUE THREAD

**Issue by H1rkul2** [porter-dev/porter#440]
# Description

can't login with GitHub 

# Location

- [x] Browser
url : https://dashboard.getporter.dev/login

# Steps to reproduce

1. go to https://dashboard.getporter.dev/login
2. Log in with GitHub
3. page reload with status code 403 in the devtool

# Additional Details
browser info : Version 1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/52507296/112681960-b1c62900-8e6f-11eb-8571-aab935657133.png)

**Comment by abelanger5** [comment]
Thanks for the bug report @H1rkul2 -- could you try clearing your cookies and seeing if you're still unable to log in? I believe this is due to the cookie-based session not updating properly after log in with Github.

**Comment by H1rkul2** [comment]
thank you @abelanger5  it fixed the problem
