### ISSUE TITLE
basic node type selector for AWS during provisioning

### ISSUE THREAD

**Issue by jusrhee** [porter-dev/porter#473]
# Location

- [X] Browser
- [ ] CLI
- [X] API

# Requirements
Add a basic selector to the AWS provisioner form for node type (t2.micro, t2.medium, t3.large, t3.xlarge).

# Additional Details

**Comment by abelanger5** [comment]
Fixed by #475 -- note that `t2.micro` is not supported due to kubelet requirements (would leave pretty much no room for applications)
