### ISSUE TITLE
Empty Procfile blocks user from launching without procfile/dockerfile

### ISSUE THREAD

**Issue by abelanger5** [porter-dev/porter#559]
# Description

Can't launch service with an empty procfile. 

# Location

- [X] Browser
- [ ] CLI
- [ ] API

# Steps to reproduce

1. Create an empty procfile in a repo
2. Attempt to launch on Porter

**Comment by igalakhov** [comment]
Logically, is it okay to treat a folder with an empty Procfile the same as a folder that has no Procfile? If that's the case, the fix should be really simple.

**Comment by abelanger5** [comment]
> Logically, is it okay to treat a folder with an empty Procfile the same as a folder that has no Procfile?

Yes, certainly.
