### ISSUE TITLE
Include a link to crontab.guru on the page with cron schedules for reference

### ISSUE THREAD

**Issue by avaitla** [porter-dev/porter#650]
# Location

- [x] Browser
- [ ] CLI
- [ ] API

# Requirements

Include a link to crontab.guru when creating a cronjob.

# Additional Details

I was thinking about how often I enter a wrong schedule, so this link can give folks a reference to where to go to check it. I'm not sure if this is clickable, but let me know if you'd prefer it to be.

I've sent a PR here: https://github.com/porter-dev/porter-charts/pull/1

**Comment by abelanger5** [comment]
Closed by porter-dev/porter-charts#1
