### ISSUE TITLE
Incorrect Internal Uri in different namespace

### ISSUE THREAD

**Issue by jimcru21** [porter-dev/porter#670]
# Description

Incorrect internal URI when creating an application that not exposed to external when creating in different namespace

# Location

- [*] Browser
- [ ] CLI
- [ ] API

# Steps to reproduce

1. Create an application in a different namespace

# Additional Details

The internal URI is the default even the namespace is a-staging 

![image](https://user-images.githubusercontent.com/52728901/117970031-c34d8c80-b35a-11eb-88f2-684fb1d70d76.png)

**Comment by abelanger5** [comment]
Thanks for the bug report @jimcru21! This fix has been merged into master and will be on the hosted version within the hour.
