### ISSUE TITLE
Re-run job button should be disabled for Cron Jobs

### ISSUE THREAD

**Issue by sunguroku** [porter-dev/porter#764]
# Location

- [x] Browser
- [ ] CLI
- [x] API

# Motivation
Re-running a cron job only results in template update without triggering an actual re-run. The cron schedule overrides any manual runs, which is misleading in terms of UX. Re-run feature should be disabled for a cron job, or renamed to something like "update".

# Requirements

# Additional Details

**Comment by abelanger5** [comment]
Updating the config for a cron job/job is now "Update config," while you can still trigger manual runs of either one-time jobs or cron jobs.
