### ISSUE TITLE
Env file upload not reading in every env variable

### ISSUE THREAD

**Issue by sunguroku** [porter-dev/porter#811]
# Description

# Location

- [x] Browser
- [ ] CLI
- [ ] API

# Steps to reproduce

1. Read in an env variable from a file with 30+ lines
2. This will sometimes load in only a few variables

# Additional Details

**Comment by anukul-plivo** [comment]
Hi! Can I try this?

**Comment by anukul** [comment]
Hi! Can I try this?

**Comment by abelanger5** [comment]
Yes! Just assigned it to you. 

Note that there's a #contributing channel in the Discord if you run into any issues.

**Comment by anukul** [comment]
@abelanger5 Can you maybe help me reproduce this? I did not see this behavior:

https://user-images.githubusercontent.com/44864521/125178474-dc5fa600-e202-11eb-9360-0237b89ae3a0.mov

However, I did notice a separate issue that might be related - https://github.com/porter-dev/porter/issues/876

**Comment by abelanger5** [comment]
I believe copying from the file may stop when a duplicate key is encountered, see here:

https://www.loom.com/share/1c0169e33788464f917687cb59fdfc7d

I'm not sure if @sunguroku was experiencing a different error?

**Comment by anukul** [comment]
@abelanger5 Oh right, missed this. Just made a PR.
