### ISSUE TITLE
Initial push to GCR from Porter GHA appears to fail

### ISSUE THREAD

**Issue by jusrhee** [porter-dev/porter#857]
# Description

If a user provisions GCR through Porter (or has a registry with no images) the initial container image push from our GHA appears to fail.

# Location

- [ ] Browser
- [X] CLI
- [ ] API

# Steps to reproduce

1. Provision to GCP through Porter (GKE + GCR) - ensure that no images exist in the GCR instance
2. Deploy an application from a connected repo
3. GHA fails on image push

# Additional Details

**Comment by abelanger5** [comment]
Closed by #1055
