### ISSUE TITLE
first pod keeps getting selected on status tab when you click on different pods

### ISSUE THREAD

**Issue by sunguroku** [porter-dev/porter#884]
# Description

# Location

- [x] Browser
- [ ] CLI
- [ ] API

# Steps to reproduce

1. Create a deployment with logs constantly streaming in for all pods
2. Click on a pod that's not the first one listed.
3. Even if you click on a different pod, the selectedpod will be the first pod on the list for the first few times

# Additional Details

**Comment by jnfrati** [comment]
This is a replica of how the bug looks like. After entering the application page if you want to select another pod it will automatically change to the first one

https://user-images.githubusercontent.com/23369263/125638470-d95f600e-b81c-4d28-88ed-4b04279bff80.mp4
