### ISSUE TITLE
k8s manifests not scrollable in "Manifests" tab

### ISSUE THREAD

**Issue by jusrhee** [porter-dev/porter#905]
# Description

If a Helm chart has many k8s objects, the user cannot scroll the list of objects to select the manifests:
![image](https://user-images.githubusercontent.com/22849518/126562613-07a4a83d-8bb5-4e11-8fc7-6c14f9cdeeaa.png)

# Location

- [X] Browser
- [ ] CLI
- [ ] API

# Steps to reproduce

Expand a chart with many manifests (e.g., Prometheus) and select the "Manifests" tab.

# Additional Details

**Comment by jnfrati** [comment]
Closed by #896
