### ISSUE TITLE
GitHub OAuth with custom domain crashes when trying to connect repositories

### ISSUE THREAD

**Issue by harshzalavadiya** [porter-dev/porter#967]
# Description
I was trying out on premise setup and initially faced issue with custom domain oAuth URL but from discord team I was able to fix that one easily so thank you for that!

![porter-testing](https://user-images.githubusercontent.com/5774849/128154560-d7350fcc-1b7d-4fab-89e5-efce3acf8963.gif)

I have created GitHub OAuth application in order to authorize that works as expected now but when I try to authorize repositories local porter server throws error as below

my current setup is nginx proxying porter dashboard on :8080 w/ letsencrypt SSL enabled

also I have documentaed some steps while trying to setup on premise if that helps to debug this https://gist.github.com/harshzalavadiya/05a701c045108bbc45e58965821047df

<details>
  <summary>Logs</summary>
```log
2021/08/04 08:54:00 http: panic serving 127.0.0.1:34152: runtime error: invalid memory address or nil pointer dereference
goroutine 7745 [running]:
net/http.(*conn).serve.func1(0xc00036a0a0)
  /opt/hostedtoolcache/go/1.15.14/x64/src/net/http/server.go:1801 +0x147
panic(0x3586700, 0x4ed1c10)
  /opt/hostedtoolcache/go/1.15.14/x64/src/runtime/panic.go:975 +0x47a
github.com/porter-dev/porter/server/api.(*App).HandleGithubAppOauthInit(0xc000ada700, 0x3d719a0, 0xc0022ea1e0, 0xc001499800)
  /home/runner/work/porter/porter/server/api/integration_handler.go:483 +0x4d
net/http.HandlerFunc.ServeHTTP(0xc000ae6cf0, 0x3d719a0, 0xc0022ea1e0, 0xc001499800)
  /opt/hostedtoolcache/go/1.15.14/x64/src/net/http/server.go:2042 +0x44
github.com/porter-dev/porter/server/middleware/requestlog.(*Handler).ServeHTTP(0xc000ae4d40, 0x3d81560, 0xc000678000, 0xc001499600)
  /home/runner/work/porter/porter/server/middleware/requestlog/handler.go:49 +0x338
github.com/go-chi/chi/middleware.Timeout.func1.1(0x3d81560, 0xc000678000, 0xc001499500)
  /home/runner/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/middleware/timeout.go:45 +0x1cf
net/http.HandlerFunc.ServeHTTP(0xc000ae4d60, 0x3d81560, 0xc000678000, 0xc001499500)
  /opt/hostedtoolcache/go/1.15.14/x64/src/net/http/server.go:2042 +0x44
github.com/go-chi/chi.(*ChainHandler).ServeHTTP(0xc000aec100, 0x3d81560, 0xc000678000, 0xc001499500)
  /home/runner/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/chain.go:31 +0x52
github.com/go-chi/chi.(*Mux).routeHTTP(0xc00016ad80, 0x3d81560, 0xc000678000, 0xc001499500)
  /home/runner/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x28b
net/http.HandlerFunc.ServeHTTP(0xc000ae6970, 0x3d81560, 0xc000678000, 0xc001499500)
  /opt/hostedtoolcache/go/1.15.14/x64/src/net/http/server.go:2042 +0x44
github.com/porter-dev/porter/server/middleware.ContentTypeJSON.func1(0x3d81560, 0xc000678000, 0xc001499500)
  /home/runner/work/porter/porter/server/middleware/json.go:9 +0x131
net/http.HandlerFunc.ServeHTTP(0xc000ae42a0, 0x3d81560, 0xc000678000, 0xc001499500)
  /opt/hostedtoolcache/go/1.15.14/x64/src/net/http/server.go:2042 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00016ad80, 0x3d81560, 0xc000678000, 0xc001499500)
  /home/runner/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:70 +0x50c
github.com/go-chi/chi.(*Mux).Mount.func1(0x3d81560, 0xc000678000, 0xc001499500)
  /home/runner/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:298 +0x122
net/http.HandlerFunc.ServeHTTP(0xc000afcd60, 0x3d81560, 0xc000678000, 0xc001499500)
  /opt/hostedtoolcache/go/1.15.14/x64/src/net/http/server.go:2042 +0x44
github.com/go-chi/chi.(*Mux).routeHTTP(0xc00016ad20, 0x3d81560, 0xc000678000, 0xc001499500)
  /home/runner/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x28b
net/http.HandlerFunc.ServeHTTP(0xc000afa4e0, 0x3d81560, 0xc000678000, 0xc001499500)
  /opt/hostedtoolcache/go/1.15.14/x64/src/net/http/server.go:2042 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc00016ad20, 0x3d81560, 0xc000678000, 0xc001499100)
  /home/runner/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:86 +0x2d1
net/http.serverHandler.ServeHTTP(0xc0006782a0, 0x3d81560, 0xc000678000, 0xc001499100)
  /opt/hostedtoolcache/go/1.15.14/x64/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc00036a0a0, 0x3d8e920, 0xc0008bc000)
  /opt/hostedtoolcache/go/1.15.14/x64/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
  /opt/hostedtoolcache/go/1.15.14/x64/src/net/http/server.go:2969 +0x36c
```
</details>

# Location

- [x] Browser
- [ ] CLI
- [ ] API

# Steps to reproduce

1. Go to Account Settings
2. Try to authorize repositories
3. Error!

# Additional Details
I was able to run application with custom docker registry but while creating service I was constantly getting for this missing tables when service was created and also while creating webhook for any running service `releases`

also it accidently launched two services instead of one

![image](https://user-images.githubusercontent.com/5774849/128155322-0d41f1f2-b7ae-4bdc-9860-67a2e065fd13.png)

also this project is amazing and game changer for everyone

**Comment by abelanger5** [comment]
Thanks for checking it out @harshzalavadiya! 

It seems like there are a few issues here:
1. Regarding the Github repositories issues, I apologize for not updating the documentation about this. While the OAuth app is required to enable Github login, a separate Github App is now used for the Github repository integrations. I have updated the docs to reflect this: https://docs.porter.run/docs/github#setting-up-github-repository-integrations. You will have to set these environment variables to get this working -- let me know if this gives you any trouble!
2. For the missing tables issue, I was able to track down this bug. It seems that we are not adding the `Release` table in the automigration [here](https://github.com/porter-dev/porter/blob/181e9e36758b9850766d36f4eb24f35ca705b5f8/cmd/app/main.go#L48), but we are doing it in a migration script [here](https://github.com/porter-dev/porter/blob/181e9e36758b9850766d36f4eb24f35ca705b5f8/cmd/migrate/main.go#L32), which is why we did not catch this. I'll be making a PR that fixes this, and this will require building a new release (`v0.6.2`).

I'll update you when this fix has been released!

**Comment by harshzalavadiya** [comment]
@abelanger5 thank you for quick response, I'll try to verify this and let you know if any issue comes up

**Comment by harshzalavadiya** [comment]
@abelanger5 Updated instructions works :tada: 

---

I also found out that we don't have to create two `Github OAuth` and `GitHub App` seprately since `GitHub App` can also include `OAuth` by default we can add both callback URL's and it works as expected

![image](https://user-images.githubusercontent.com/5774849/128602722-311236e5-3ffb-4886-98b7-0854f933b97f.png)

---

For `GitHub App` private key path is not being overwritten from enviroment variable, as a workaround I copied it to `/porter/docker/github_app_private_key.pem` 

![image](https://user-images.githubusercontent.com/5774849/128602921-fd35c384-13b4-4bc7-9633-582059bbd55b.png)
